model: yolov8m
epochs: 50
batch: 16
imgsz: 416
patience: 10
device: 0
optimizer: SGD
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005

augmentation:
  mosaic: 1.0
  fliplr: 0.5
  flipud: 0.0
  degrees: 15
  translate: 0.1
  scale: 0.5
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
